Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%q': {}
