- id: 1
  name: TwinkleRibbon
  kana: トゥインクルリボン
- id: 2
  name: CandyAlamode
  kana: キャンディアラモード
- id: 3
  name: HolicTrick
  kana: ホリックトリック
- id: 4
  name: BabyMonster
  kana: ベイビーモンスター
- id: 5
  name: FortuneParty
  kana: フォーチュンパーティー
- id: 6
  name: MarionetteMu
  kana: マリオネットミュー
- id: 7
  name: DreamingGirl
  kana: ドリーミングガール
- id: 8
  name: PrismStone
  kana: プリズムストーン
- id: 9
  name: SilkyHeart
  kana: シルキーハート
- id: 10
  name: HolicTrick classic
  kana: ホリックトリッククラシック
- id: 11
  name: CocoFlower
  kana: ココフラワー
- id: 12
  name: CandyAlamode more
  kana: キャンディアラモードモア
- id: 13
  name: BrilliantPrince
  kana: ブリリアントプリンス
- id: 14
  name: RosetteJewel
  kana: ロゼットジュエル
- id: 15
  name: LOVEDEVI
  kana: ラブデビ
- id: 16
  name: DearCrown
  kana: ディアクラウン
- id: 17
  name: SunnyZoo
  kana: サニーズー
- id: 18
  name: TwinkleRibbon Sweet
  kana: トゥインクルリボンスウィート
