- id: 1
  slug: lovely
  name: ラブリー
  color: pink
- id: 2
  slug: pop
  name: ポップ
  color: blue
- id: 3
  slug: cool
  name: クール
  color: purple
- id: 4
  slug: natural
  name: ナチュラル
  color: green
- id: 5
  slug: celeb
  name: セレブ
  color: yellow
- id: 6
  slug: premium
  name: プレミアム
  color: white
