- id: 1
  slug: laala
  name: 真中らぁら
  cast_name: 茜屋日海夏
- id: 2
  slug: mirei
  name: 南みれぃ
  cast_name: 芹澤優
- id: 3
  slug: sophie
  name: 北条そふぃ
  cast_name: 久保田未夢
- id: 4
  slug: sion
  name: 東堂シオン
  cast_name: 山北早紀
- id: 5
  slug: dorothy
  name: ドロシー・ウェスト
  cast_name: 澁谷梓希
- id: 6
  slug: reona
  name: レオナ・ウェスト
  cast_name: 若井友希